parameters:
 - name: Environment
   default: 'test' 

name: Pipeline-$(Build.DefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)

pr: none
trigger: none

variables:
   AdoEnvironment: 'test-ado'

pool: 'Azure Pipelines'


stages:
- stage: Stage_${{ parameters.Environment }} 
  displayName: Stage - ${{ parameters.Environment }}
  dependsOn: []

  jobs:  
  - deployment: JobDataBuild
    pool:
      vmImage: 'windows-latest'
    displayName: Job - Data Build
    dependsOn: []

    environment: ${{ variables.AdoEnvironment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: VSBuild@1
            displayName: 'Visual Studio Build sln file '
            inputs:
              vsVersion: 17.0
              solution: DatabaseForSimpliedYaml/DatabaseForSimpliedYaml.sln
              #msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
              platform: 'any cpu'
              configuration: release

          - task: CopyFiles@2
            displayName: 'Copy Files to:  $(Build.ArtifactStagingDirectory)'
            inputs:
              SourceFolder: '/DatabaseForSimpliedYaml/DatabaseExample/bin/release'
              Contents: '**.dacpac'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Pipeline Artifact'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifact: 'dacpac-built'
