parameters:
 - name: Environment
   default: 'Test' 
   values:
   - Test
   - UAT
   - Prod


name: Pipeline-$(Build.DefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)

pr: none
trigger: none

variables:
   AdoEnvironment: '${{ parameters.Environment }}-ado'

pool: 'Azure Pipelines'


stages:
- stage: Stage_${{ parameters.Environment }} 
  displayName: Stage - ${{ parameters.Environment }}
  dependsOn: []

  jobs:

  - template: .\Build-Database.yml
    parameters: 
     Environment: ${{ parameters.Environment }} 

  - template: .\Deploy-Database.yml
    parameters: 
     Environment: ${{ parameters.Environment }} 