name: Database Deployment

on:
  workflow_dispatch:
    inputs:
       environment:
        description: 'Environment'
        type: environment
  push:
    branches:
      - feature/*  
  
env:
      SQL_SERVER_NAME: ${{ secrets.SQL_SERVER_NAME }}
      CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      CERT: ${{ secrets.CERT }}
      WORKING_DIRECTORY: DatabaseForSimpliedYaml
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}

jobs:
  build :
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Navigate to Workspace
        run: |
          cd DatabaseForSimpliedYaml
          pwd

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
      

      - name: Build DACPAC
        run: msbuild 'DatabaseForSimpliedYaml/DatabaseForSimpliedYaml.sln' /p:TargetFrameworkVersion=v4.7.1 /p:DSP=Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name:  SQLDB
          path: ${{ github.workspace }}/DatabaseForSimpliedYaml/DatabaseExample/bin/debug/

  deploy: 
    needs: build
    environment: sandbox
    runs-on: windows-latest

    steps:
      - name: Az Log in
        shell: bash
        run: |
          az login --service-principal -u ${{ env.CLIENT_ID }} -p ${{ env.CLIENT_SECRET }} --tenant ${{ env.TENANT_ID }}

      - name: download artifact containing dacpac
        uses: actions/download-artifact@v3.0.2
        with:
          name: SQLDB

      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2.1
        with:
          connection-string: '${{ secrets.CONNECTION_STRING }}'
          path: './DatabaseExample.dacpac'
          action: publish
          arguments: '/p:DropObjectsNotInSource=true'
