name: Deploy to Azure

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build :
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Navigate to Workspace
        run: |
          cd DatabaseForSimpliedYaml
          pwd

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
      

      - name: Build DACPAC
        run: msbuild 'DatabaseForSimpliedYaml/DatabaseForSimpliedYaml.sln' /p:TargetFrameworkVersion=v4.7.1 /p:DSP=Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name:  SQLDB
          path: ${{ github.workspace }}/DatabaseForSimpliedYaml/DatabaseExample/bin/debug/
